apiVersion: v1
kind: Secret
metadata:
  name: postgres-user-data
  namespace: standard
type: Opaque
data:
  user: YWRtaW4=
  password: cGFzc3dvcmQ=

---

apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-user-data
  namespace: standard
type: Opaque
data:
  password: YWRtaW4=

